Add Kindling Emitter
FireToolchain/Fire pull request #1
Opened 2023-07-01 15:56 UTC by akarahdev

Currently, Fire has no easy way of emitting Kindling besides just generating a string. However, I made a group of classes that aim to drastically simplify this process - allowing you to generate Kotlin classes that can be emitted into valid Kindling. It's not fully done, as I'm unsure if the Kindling it emits is valid.

Input:
```
val toEmit = KindlingHeader.PlayerEvent("join", arrayOf(
        KindlingAction.PlayerAction("SendMessage", "", arrayOf(KindlingArgument.Text("hi %default"))),
    ))

    val output = emitValue(emitHeader(toEmit))
    println(output)
```
Output:
```
( player-event "join" ( ( player-action "SendMessage" "" ( ( text "hi %default" ) ) ) ) )
```

2023-07-01 15:57 UTC, akarahdev commented
Wait, I forgot to finish some of the actions. I'll get to that in a bit.

2023-07-01 22:05 UTC, ashlikatt requested changes
Looks mostly good, just would like to see better organization and documentation. This is sure to help a ton once we actually get to a point where we're generating Kindling!

2023-07-01 22:05 UTC, ashlikatt commented on src/main/kotlin/dev/ashli/fire/parser/emitter/KindlingEmitter.kt
I would like to see this broken up into different files with JavaDocs to explain their use, even if trivial.

2023-07-02 01:31 UTC, akarahdev commented
Alright, thanks for the input! I finished the actions, fixed some issues, reorganized, and added JavaDocs for all of it.

2023-07-03 01:52 UTC, ashlikatt approved these changes
Much better, love it!

2023-07-03 01:52 UTC, merged